version: '3.7'

services:
   #Stack PHP
   php:
      build: ./docker/php-fpm/
      volumes:
         - ./:/srv/http
         - ~/.composer/cache:/root/.composer/cache
      ports:
      - "9022:22"
      environment:
      - PHP_IDE_CONFIG=serverName=tennisRefacto-docker
      - COMPOSER_MEMORY_LIMIT=-1
      - SSH_AUTH_SOCK=/root/.ssh/socket
      env_file:
      - '.env'

   #Stack NGINX
   nginx:
      image: nginx
      links:
      - php:php-fpm-stack
      volumes:
      - ./docker/conf/nginx.conf:/nginx.conf
      ports:
      - "1337:80"
      command: nginx -c /nginx.conf
